### ISSUE TITLE
词性标注结果异常

### ISSUE THREAD

**Issue by 8TIBi1** [YanqiangWang/NLP-Summer-Course#1]
带佬宁好，我用您的代码跑的其他的生成训练集和测试集都正常，但是最后生成的结果集要么是空的，要么结果的词性全是“/”，特向您请教。

**Comment by YanqiangWang** [comment]
你是在博客园留言的那个同学是吧，我在那儿回复你了，那我把这个Issue关了

**Comment by 8TIBi1** [comment]
哈哈哈，是的，因为不确定宁还上不上博客园，就github也开了issue，感谢宁。
